export { default as CyberAvatar } from './CyberAvatar.vue'
export { default as SterileCyberAvatar } from './SterileCyberAvatar.vue'
export { default as SterileAvatar } from './SterileAvatar.vue'
export { default as BlueprintAvatar } from './BlueprintAvatar.vue'
export { default as BrutalAvatar } from './BrutalAvatar.vue'
export { default as NoirAvatar } from './NoirAvatar.vue'
